version: "2"

services:
  chain-mysql:
    image: mysql:5.7.18
    container_name: chain-mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=Hwt123456!"
      - "MYSQL_DATABASE=api_data"
    volumes:  
      - ./apps/mysql/mydir:/mydir
      - ./apps/mysql/datadir:/var/lib/mysql
      - ./apps/mysql/conf/my.cnf:/etc/my.cnf
      # 数据库还原目录 可将需要还原的sql文件放在这里
      - ./apps/mysql/source:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306" # 与配置文件保持一致
    restart: always
 
  spider:
    build: .  # 使用同级目录下的Dockerfile
    container_name: chain-spider
    links:
      - chain-mysql
    depends_on:  # 依赖关系
      - chain-mysql
    environment:
      - DEBUG=False
    restart: always

